nodeLinker: node-modules

npmScopes:
    fortawesome:
        npmAlwaysAuth: true
        npmAuthToken: '${FONTAWESOME_NPM_AUTH_TOKEN}'
        npmRegistryServer: "https://npm.fontawesome.com/"

yarnPath: .yarn/releases/yarn-3.4.1.cjs
