service: energy-dashboard-web

plugins:
    - serverless-apigw-binary
    - serverless-offline

provider:
    name: aws
    runtime: nodejs16.x
    memorySize: 512
    timeout: 30
    stage: dev
    region: eu-central-1

package:
    exclude:
        - src/**
        - node_modules/**
        - e2e/**
        - coverage/**
        - .angular/**
        - .idea/**
        - .vscode/**
        - .git/**
        - .yarn/**
        - '!node_modules/@angular/**'
        - '!node_modules/@nguniversal/**'
        - '!node_modules/express/**'
        - '!node_modules/fs/**'
        - '!node_modules/path/**'
        - '!node_modules/@vendia/**'
        - '!node_modules/aws-serverless-express/**'
        - '!node_modules/binary-case/**'
        - '!node_modules/type-is/**'
        - '!node_modules/media-typer/**'
        - '!node_modules/mime-types/**'
        - '!node_modules/mime-db/**'
        - '!node_modules/zone.js/**'

custom:
    apigwBinary:
        types:
            - '*/*'

functions:
    api:
        handler: lambda.handler
        events:
            -   http: ANY {proxy+}
            -   http: ANY /
