service: energy-dashboard-web

plugins:
    - serverless-apigw-binary
    - serverless-offline
    - 'serverless-plugin-lambda-insights'
    - 'serverless-plugin-aws-alerts'

provider:
    name: aws
    runtime: nodejs18.x
    memorySize: 512
    timeout: 30
    stage: dev
    region: eu-central-1

package:
    exclude:
        - src/**
        - node_modules/**
        - e2e/**
        - coverage/**
        - .angular/**
        - .idea/**
        - .vscode/**
        - .git/**
        - .yarn/**
        - '!node_modules/@angular/**'
        - '!node_modules/@nguniversal/**'
        - '!node_modules/express/**'
        - '!node_modules/fs/**'
        - '!node_modules/path/**'
        - '!node_modules/@vendia/**'
        - '!node_modules/aws-serverless-express/**'
        - '!node_modules/binary-case/**'
        - '!node_modules/type-is/**'
        - '!node_modules/media-typer/**'
        - '!node_modules/mime-types/**'
        - '!node_modules/mime-db/**'
        - '!node_modules/zone.js/**'

custom:
    apigwBinary:
        types:
            - '*/*'
    lambdaInsights:
        defaultLambdaInsights: true #enables Lambda Insights for all functions
    alerts:
        topics:
            alarm:
                topic: ${self:service}-${opt:stage}-alerts-alarm
                notifications:
                    -   protocol: email
                        endpoint: bas@ti8m.ch
                    -   protocol: email
                        endpoint: energiedashboard@ti8m.ch
                    -   protocol: email
                        endpoint: yannik.inniger@ti8m.ch
        alarms:
            - functionErrors
            - functionThrottles

functions:
    api:
        handler: lambda.handler
        events:
            -   http: ANY {proxy+}
            -   http: ANY /
